require 'nicorithner.options'
require 'nicorithner.keymaps'
require "nicorithner.plugins"
require "nicorithner.colorscheme"
require "nicorithner.cmp"
require "nicorithner.lsp"
require "nicorithner.telescope"
require "nicorithner.treesitter"
require "nicorithner.autopairs"
require "nicorithner.comment"
require "nicorithner.gitsigns"
require "nicorithner.nvim-tree"
require "nicorithner.bufferline"
